include:
  - project: muni-kypo-images/ci-cd-virtual-images
    file: .gitlab-ci-template.yml

variables:
  NAME: "ubuntu"
  TYPE: "linux"
  DISTRO: "ubuntu"

build-vbox:
  extends: .build
  script:
    - PACKER_LOG=1 packer build -only=vbox $NAME.json
  artifacts:
    paths:
      - target-vbox/*

